### ISSUE TITLE
Lower case character support

### ISSUE THREAD

**Issue by thematthewreed** [normaldotcom/cantact-fw#1]
Currently only upper case characters are parsed correctly by the device, but it also accepts lower case characters without any warnings and sends incorrect data onto the bus.

Example:
Sending
t1231ff\r
Transmits CAN message
ID: 123 DLC: 1 Data: 0x1F

**Comment by normaldotcom** [comment]
Fixed in bc5da3d2a293bc6991b4fc0e6a0f5c65c5a22728
