### ISSUE TITLE
RTR messages are received with the "T" prefix instead of "R".

### ISSUE THREAD

**Issue by Wybe-Westra** [normaldotcom/cantact-fw#10]
While testing I noticed that RTR (Remote Transmission Request) messages are reported with the "T" prefix, while they should have the "R" prefix.

The firmware checks if something is an RTR message, by looking at the `frame->RTR` field.

This is compared to `CAN_RTR_REMOTE` (0x02).
However, while the RTR bit is indeed the 2nd bit in the hardware CAN register, this is not the value the RTR field will have.
The `frame->RTR` value will be 1 for RTR messages, and 0 for non-RTR messages.

https://github.com/normaldotcom/cantact-fw/blob/1205aa622dda55296ec5f9f8234387f33f19a0c2/src/slcan.c#L28

**Comment by normaldotcom** [comment]
Good find--the old HAL CAN library did indeed set RTR to 0 or 1. I just made a fairly significant commit 100f0fe01b9c088ac298c8b7f44c94a50e78ceb9 that updates the HAL CAN library (amongst other things) and the updated library correctly sets the RTR field to CAN_RTR_REMOTE. I'm still doing testing on this latest commit, but so far everything looks good. Let me know if you run into any issues!
