### ISSUE TITLE
Cannot find b158aa7 commit in this repository

### ISSUE THREAD

**Issue by oPiZiL** [normaldotcom/cantact-fw#14]
From the [Updater web](https://canable.io/updater/canable2.html)
![image](https://github.com/normaldotcom/canable-fw/assets/3918631/93449762-3dff-4909-baad-aa5264860441)

but i cannot found it.

**Comment by normaldotcom** [comment]
Good catch--fixed the link. The CANable 2.0 has a different repo for firmware which you can find here: [https://github.com/normaldotcom/canable2-fw](https://github.com/normaldotcom/canable2-fw)

Thanks!
